version: '3.6'
services:
  node-bulgakov:
    container_name: node-bulgakov
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $GATE_LISTEN_PORT:$GATE_LISTEN_PORT
      - $FRONTEND_GATE_LISTEN_PORT:$FRONTEND_GATE_LISTEN_PORT
    environment:
      - NOTIFY_CONNECT_STRING
      - GATE_LISTEN_PORT
      - FRONTEND_GATE_LISTEN_PORT
      - DAY_START
      - BLOCKCHAIN_SUBSCRIBE_TIMEOUT
      - BLOCKCHAIN_NODE_ADDRESS
      - METRICS_HOST
      - METRICS_PORT
